/**
 * Canonical append-only audit taxonomy. Values intentionally remain strings so historical records
 * written before this taxonomy can still be read, while all new mutations share one vocabulary.
 */
export const auditActions = {
  AWS_CONNECTION_CREATED: 'AWS_CONNECTION_CREATED',
  AWS_CONNECTION_VERIFIED: 'AWS_CONNECTION_VERIFIED',
  AWS_CONNECTION_VERIFICATION_FAILED: 'AWS_CONNECTION_VERIFICATION_FAILED',
  AWS_CONNECTION_DISCONNECTED: 'AWS_CONNECTION_DISCONNECTED',
  AGENT_CREATED: 'AGENT_CREATED',
  AGENT_CONFIGURATION_UPDATED: 'AGENT_CONFIGURATION_UPDATED',
  DEPLOYMENT_REQUESTED: 'DEPLOYMENT_REQUESTED',
  DEPLOYMENT_SUCCEEDED: 'DEPLOYMENT_SUCCEEDED',
  DEPLOYMENT_FAILED: 'DEPLOYMENT_FAILED',
  AGENT_INVOKED: 'AGENT_INVOKED',
  AGENT_INVOCATION_FAILED: 'AGENT_INVOCATION_FAILED',
  POLICY_DENIED: 'POLICY_DENIED',
  ROLLBACK_REQUESTED: 'ROLLBACK_REQUESTED',
  ROLLBACK_SUCCEEDED: 'ROLLBACK_SUCCEEDED',
  ROLLBACK_FAILED: 'ROLLBACK_FAILED',
  UNDEPLOY_REQUESTED: 'UNDEPLOY_REQUESTED',
  UNDEPLOY_SUCCEEDED: 'UNDEPLOY_SUCCEEDED',
  UNDEPLOY_FAILED: 'UNDEPLOY_FAILED'
} as const;

export type AuditAction = (typeof auditActions)[keyof typeof auditActions];
