packages:
  - apps/*
  - services/*
  - agents/*
  - packages/*
  - infrastructure/*

allowBuilds:
  '@astryxdesign/cli': set this to true or false
  '@astryxdesign/core': set this to true or false
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - aws-cdk@2.1135.1
