packages:
  - apps/*
  - services/*
  - agents/*
  - packages/*
  - infrastructure/*

allowBuilds:
  '@astryxdesign/cli': false
  '@astryxdesign/core': false
  esbuild: true
  protobufjs: false
  sharp: true

minimumReleaseAgeExclude:
  - aws-cdk@2.1135.1
